version: '3.7'
services: 
    db:
        image: postgres
        restart: always
        volumes: 
            - c:\db:/var/lib/postgresql/data
        environment: 
            POSTGRES_PASSWORD: 123
        ports: 
            - 5432:5432

    